### ISSUE TITLE
t.fill is not a function

### ISSUE THREAD

**Issue by mateusz-peczkowski** [dnwjn/nova-button#21]
Hey. First of all nice job! ;) It is working very well.

I have one small issue. I connect your package for button with nova settings (OptimistDigital\NovaSettings\NovaSettings) and problem is that when I am trying to save a settings page where I have your button it don't allow me and in console I see:
`TypeError: t.fill is not a function`

It is only with your package. Are you able to help me with that?

`Button::make('Fetch Data', 'FetchSubscanData')
                ->style('primary-outline')
                ->successStyle('success-outline')
                ->errorStyle('danger-outline')
                ->loadingStyle('warning-outline')
                ->reload(),`

**Comment by dnwjn** [comment]
Hi @mateusz-peczkowski , thank you for the kind words! I will look into your issue asap!

**Comment by dnwjn** [comment]
@mateusz-peczkowski Version [3.1.0](https://github.com/dnwjn/nova-button/releases/tag/3.1.0) has just been released, containing #22 that might solve your problem. As I was unable to reproduce your issue, could you try out the new version and see if that solves it?

**Comment by dnwjn** [comment]
Closed because of inactivity.
