### ISSUE TITLE
Allow to work with Nova v4

### ISSUE THREAD

**Issue by dnwjn** [dnwjn/nova-button#24]
Currently the button does not work in Nova v4, which obviously needs to be fixed.

**Comment by DockerComposeFiles** [comment]
Actual the button is invisible, what can be an styling problem with tailwind

Button::make('Nova Url')->link('https://nova.laravel.com'),

![image](https://user-images.githubusercontent.com/87118951/209316877-365bbfcc-53a9-454a-b5c8-42531e006fcd.png)

**Comment by sietse85** [comment]
Nova 4 Support is available here: https://github.com/sietse85/nova-button

**Comment by dnwjn** [comment]
@DockerComposeFiles The issue has been identified and will be fixed soon. A new version will be released before the end of the week!

**Comment by dnwjn** [comment]
@DockerComposeFiles Apologies for being later than promised, but version 4.0.0 has been released: https://github.com/dnwjn/nova-button/releases/tag/4.0.0
