### ISSUE TITLE
Update to php8.2

### ISSUE THREAD

**Issue by DockerComposeFiles** [dnwjn/nova-button#25]
Can this package be updated to use php8.2?

**Comment by dnwjn** [comment]
@DockerComposeFiles Hi! Thank you for your issue, I will look into this soon and expect to release a compatible version before the end of the week!

**Comment by dnwjn** [comment]
@DockerComposeFiles I can confirm that this package works with PHP 8.2. If you do encounter any issues though, feel free to create a new issue!
