### ISSUE TITLE
`route` method is protected

### ISSUE THREAD

**Issue by benpdavison** [dnwjn/nova-button#41]
Hey,

Thanks for the package maintenance.

Just a short one, docs say you can call `route` on the Button class, however this commit https://github.com/dnwjn/nova-button/commit/fa5eccadca28a589d1bd918fa4c8cf0871a1caa0 made the method protected, and therefore you cannot call it as per the documentation.

It results in an erorr.

**Comment by dnwjn** [comment]
Hi @benpdavison! Thank you for your report. You're absolutely right!,`->route()` should be accessible. As it also needs some changes in the Vue components I need some time to fix this. I'll keep you updated!

**Comment by dnwjn** [comment]
@benpdavison After looking into this I have to be honest: I don't see why it's in the docs, because I don't see how it used to work in the past...

So, before I remove it from the docs, I want to ask you: what would your use case be for `->route()`? What do you expect from it?
